#jeg vil ikke ha hjelp fra pus
#Vi må ha kommentaren over så lenge vi ikke bruker appdynamics her, dette bør vi fikse på sikt
team: "personbruker"
name: personopplysninger-api
image: docker.adeo.no:5000/personbruker/personopplysninger-api
replicas:
  min: 1
  max: 4
  cpuThresholdPercentage: 50
port: 8080
ingress:
  enabled: true
prometheus:
  enabled: true
  path: person/personopplysninger-api/internal/prometheus
healthcheck:
  liveness:
    initialDelay: 20
    path: person/personopplysninger-api/internal/status/isAlive
  readiness:
    initialDelay: 20
    path: person/personopplysninger-api/internal/status/isAlive
resources:
  limits:
    cpu: 3
fasitResources:
  used:
  - alias: aad_b2c_clientid
    resourceType: credential
    propertyMap:
      username: NO_NAV_SECURITY_OIDC_ISSUER_SELVBETJENING_ACCEPTEDAUDIENCE
  - alias: aad_b2c_discovery
    resourceType: baseurl
    propertyMap:
      url: NO_NAV_SECURITY_OIDC_ISSUER_SELVBETJENING_DISCOVERYURL
  - alias: appres.cms
    resourceType: baseUrl
  - alias: tps-proxy.api.v1.innsyn
    resourceType: restservice
  - alias: personopplysninger-api-tps-proxy.api.v1.innsyn-apiKey
    resourceType: credential
  - alias: aareg.api
    resourceType: restservice
  - alias: ereg.api
    resourceType: restservice
  - alias: personopplysninger-api-aareg.api-apiKey
    resourceType: credential
  - alias: personopplysninger-api-ereg.api-apiKey
    resourceType: credential
  - alias: kodeverk.rest-api
    resourceType: restservice
  - alias: personopplysninger-api-kodeverk.rest-api-apiKey
    resourceType: credential
  - alias: personopplysninger-api-dkif.api-apiKey
    resourceType: credential
  - alias: dkif.api
    resourceType: restservice
  - alias: personopplysninger-api-security-token-service-token-apiKey
    resourceType: credential
  - alias: security-token-service-token
    resourceType: restservice
  - alias: srvpersonopplysninger-api
    resourceType: credential
  - alias: srvsoknadsveiviser
    resourceType: credential