spring:
  autoconfigure.exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  jersey:
    application-path: /api
server:
  servlet:
    context-path: /personopplysninger-api
management:
   endpoints.web.exposure.include: '*'
http.proxy: http://webproxy-nais.nav.no:8088
no.nav.security.oidc:
  issuers: selvbetjening
  issuer.selvbetjening:
    discoveryurl: <Hentes fra fasit>
    acceptedaudience: <Hentes fra fasit>
    cookie_name: selvbetjening-idtoken
