spring:
  autoconfigure.exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  jersey:
    application-path: /
    servlet:
      load-on-startup: 1
    type: filter
    filter:
      order: -100000
  main:
    banner-mode: "off"

metrics.web.server.auto-time-request: true
server:
  servlet:
    context-path: /person/personopplysninger-api

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      base-path: "/internal/actuator"
      exposure:
        include: ["info", "health", "prometheus", "metrics"]

http.proxy: http://webproxy-nais.nav.no:8088

logging:
  config: "classpath:logback-spring.xml"

no.nav.security.oidc:
  issuers: selvbetjening
  issuer.selvbetjening:
    discoveryurl: ${LOGINSERVICE_IDPORTEN_DISCOVERY_URL}
    acceptedaudience: ${LOGINSERVICE_IDPORTEN_AUDIENCE}
    cookie_name: selvbetjening-idtoken

MEDL_CONSUMER_TARGET_APP: "prod-fss:team-rocket:medlemskap-medl-api"
