spring:
  autoconfigure.exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  jersey:
    application-path: /
    servlet:
      load-on-startup: 1
    type: filter
    filter:
      order: -100000

server:
  port: 8080
  servlet:
    context-path: /person/personopplysninger-api

no.nav.security.oidc:
  issuers: selvbetjening
  issuer.selvbetjening:
     discoveryurl: http://metadata
     accepted_audience: aud-localhost
     cookie_name: localhost-idtoken

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      base-path: "/internal/actuator"
      exposure:
        include: ["info", "health", "prometheus", "metrics"]

TPS_PROXY_API_V1_INNSYN_URL: https://tps-proxy.nais.preprod.local/api/v1/innsyn/
PERSONOPPLYSNINGER-API-TPS-PROXY_API_V1_INNSYN-APIKEY_USERNAME: x-nav-apiKey
PERSONOPPLYSNINGER-API-TPS-PROXY_API_V1_INNSYN-APIKEY_PASSWORD: personopplysninger-api+7f584507a67f45e0a19e1b17c1b97797

kodeverk:rest-api_URL: https://api-gw-q0.oera.no/kodeverk/api/
personopplysninger-api-kodeverk.rest-api-apiKey_username: x-nav-apiKey
personopplysninger-api-kodeverk.rest-api-apiKey_password: personopplysninger-api+a678d06e23fa47a6b516956ab8a3424b
