package no.nav.personopplysninger.features.personalia.kodeverk

import org.slf4j.Logger
import org.slf4j.LoggerFactory

enum class Landkode(val beskrivelse: String) {
    //???("UOPPGITT/UKJENT"),
    ABW("ARUBA"),
    AFG("AFGHANISTAN"),
    AGO("ANGOLA"),
    AIA("ANGUILLA"),
    ALA("ÅLAND"),
    ALB("ALBANIA"),
    AND("ANDORRA"),
    ANT("DE NEDERLANDSKE ANTILLENE"),
    ARE("DE ARABISKE EMIRATER"),
    ARG("ARGENTINA"),
    ARM("ARMENIA"),
    ASM("AM. SAMOA"),
    ATG("ANTIGUA OG BARBUDA"),
    AUS("AUSTRALIA"),
    AUT("ØSTERRIKE"),
    AZE("AZERBAJDZJAN"),
    BDI("BURUNDI"),
    BEL("BELGIA"),
    BEN("BENIN"),
    BES("BONAIRE, SINT EUSTATIUS, SABA"),
    BFA("BURKINA FASO"),
    BGD("BANGLADESH"),
    BGR("BULGARIA"),
    BHR("BAHRAIN"),
    BHS("BAHAMAS"),
    BIH("BOSNIA-HERCEGOVINA"),
    BLM("SAINT BARTHELEMY"),
    BLR("HVITERUSSLAND"),
    BLZ("BELIZE"),
    BMU("BERMUDA"),
    BOL("BOLIVIA"),
    BRA("BRASIL"),
    BRB("BARBADOS"),
    BRN("BRUNEI"),
    BTN("BHUTAN"),
    BVT("BOUVETØYA"),
    BWA("BOTSWANA"),
    CAF("SENTRALAFRIKA. REP."),
    CAN("CANADA"),
    CCK("KOKOSØYENE"),
    CHE("SVEITS"),
    CHL("CHILE"),
    CHN("REPUBLIKKEN KINA"),
    CIV("ELFENBEINSKYSTEN"),
    CMR("KAMERUN"),
    COD("KONGO, DEN DEMOKR. REPUBL"),
    COG("KONGO, REPUBLIKKEN"),
    COK("COOKØYENE"),
    COL("COLOMBIA"),
    COM("KOMORENE"),
    CPV("KAPP VERDE"),
    CRI("COSTA RICA"),
    CUB("CUBA"),
    CUW("CURACAO"),
    CXR("CHRISTMASØYA"),
    CYM("CAYMANØYENE"),
    CYP("KYPROS"),
    CZE("DEN TSJEKKISKE REP."),
    DEU("TYSKLAND"),
    DJI("DJIBOUTI"),
    DMA("DOMINICA"),
    DNK("DANMARK"),
    DOM("DEN DOMINIKANSKE REP"),
    DZA("ALGERIE"),
    ECU("ECUADOR"),
    EGY("EGYPT"),
    ERI("ERITREA"),
    ESH("VEST-SAHARA"),
    ESP("SPANIA"),
    EST("ESTLAND"),
    ETH("ETIOPIA"),
    FIN("FINLAND"),
    FJI("FIJI"),
    FLK("FALKLANDSØYENE"),
    FRA("FRANKRIKE"),
    FRO("FÆRØYENE"),
    FSM("MIKRONESIAFØD."),
    GAB("GABON"),
    GBR("STORBRITANNIA"),
    GEO("GEORGIA"),
    GGY("GUERNSEY"),
    GHA("GHANA"),
    GIB("GIBRALTAR"),
    GIN("GUINEA"),
    GLP("GUADELOUPE"),
    GMB("GAMBIA"),
    GNB("GUINEA-BISSAU"),
    GNQ("EKVATORIAL-GUINEA"),
    GRC("HELLAS"),
    GRD("GRENADA"),
    GRL("GRØNLAND"),
    GTM("GUATEMALA"),
    GUF("FRANSK GUYANA"),
    GUM("GUAM"),
    GUY("GUYANA"),
    HKG("HONGKONG"),
    HMD("HEARD OG MCDONALD ØYENE"),
    HND("HONDURAS"),
    HRV("KROATIA"),
    HTI("HAITI"),
    HUN("UNGARN"),
    IDN("INDONESIA"),
    IMN("ISLE OF MAN"),
    IND("INDIA"),
    IOT("BRITISK-INDISKE HAV"),
    IRL("IRLAND"),
    IRN("IRAN"),
    IRQ("IRAK"),
    ISL("ISLAND"),
    ISR("ISRAEL"),
    ITA("ITALIA"),
    JAM("JAMAICA"),
    JEY("JERSEY"),
    JOR("JORDAN"),
    JPN("JAPAN"),
    KAZ("KAZAKHSTAN"),
    KEN("KENYA"),
    KGZ("KIRGISISTAN"),
    KHM("KAMBODSJA"),
    KIR("KIRIBATI"),
    KNA("ST.KITTS OG NEVIS"),
    KOR("SØR-KOREA"),
    KWT("KUWAIT"),
    LAO("LAOS"),
    LBN("LIBANON"),
    LBR("LIBERIA"),
    LBY("LIBYA"),
    LCA("ST. LUCIA"),
    LIE("LIECHTENSTEIN"),
    LKA("SRI LANKA"),
    LSO("LESOTHO"),
    LTU("LITAUEN"),
    LUX("LUXEMBOURG"),
    LVA("LATVIA"),
    MAC("MACAO"),
    MAF("SAINT MARTIN"),
    MAR("MAROKKO"),
    MCO("MONACO"),
    MDA("MOLDOVA"),
    MDG("MADAGASKAR"),
    MDV("MALDIVENE"),
    MEX("MEXICO"),
    MHL("MARSHALLØYENE"),
    MKD("MAKEDONIA"),
    MLI("MALI"),
    MLT("MALTA"),
    MMR("MYANMAR (BURMA)"),
    MNE("MONTENEGRO"),
    MNG("MONGOLIA"),
    MNP("NORD-MARIANENE"),
    MOZ("MOSAMBIK"),
    MRT("MAURITANIA"),
    MSR("MONSERRAT"),
    MTQ("MARTINIQUE"),
    MUS("MAURITIUS"),
    MWI("MALAWI"),
    MYS("MALAYSIA"),
    MYT("MAYOTTE"),
    NAM("NAMIBIA"),
    NCL("NY-KALEDONIA"),
    NER("NIGER"),
    NFK("NORFOLKØYA"),
    NGA("NIGERIA"),
    NIC("NICARAGUA"),
    NIU("NIUE"),
    NLD("NEDERLAND"),
    NOR("NORGE"),
    NPL("NEPAL"),
    NRU("NAURU"),
    NZL("NEW ZEALAND"),
    OMN("OMAN"),
    PAK("PAKISTAN"),
    PAN("PANAMA"),
    PCN("PITCAIRN"),
    PER("PERU"),
    PHL("FILIPPINENE"),
    PLW("PALAU"),
    PNG("PAPUA NY-GUINEA"),
    POL("POLEN"),
    PRI("PUERTO RICO"),
    PRK("NORD-KOREA"),
    PRT("PORTUGAL"),
    PRY("PARAGUAY"),
    PSE("DET PALESTINSKE OMRÅDET"),
    PYF("FRANSK POLYNESIA"),
    QAT("QATAR"),
    REU("REUNION"),
    ROU("ROMANIA"),
    RUS("RUSSLAND"),
    RWA("RWANDA"),
    SAU("SAUDI-ARABIA"),
    SCG("SERBIA OG MONTENEGRO"),
    SDN("SUDAN"),
    SEN("SENEGAL"),
    SGP("SINGAPORE"),
    SGS("SØR-GEORGIA OG SØR-SANDWICHØYE"),
    SHN("ST. HELENA"),
    SJM("SVALBARD OG JAN MAYEN"),
    SLB("SALOMONØYENE"),
    SLE("SIERRA LEONE"),
    SLV("EL SALVADOR"),
    SMR("SAN MARINO"),
    SOM("SOMALIA"),
    SPM("ST-PIERRE OG MIQUELON"),
    SRB("SERBIA"),
    SSD("SØR-SUDAN"),
    STP("SAO TOME OG PRINCIPE"),
    SUR("SURINAM"),
    SVK("SLOVAKIA"),
    SVN("SLOVENIA"),
    SWE("SVERIGE"),
    SWZ("SWAZILAND"),
    SXM("SINT MAARTEN"),
    SYC("SEYCHELLENE"),
    SYR("SYRIA"),
    TCA("TURKS/CAICOSØYENE"),
    TCD("TSJAD"),
    TGO("TOGO"),
    THA("THAILAND"),
    TJK("TADZJIKISTAN"),
    TKL("TOKELAU"),
    TKM("TURKMENISTAN"),
    TLS("ØST-TIMOR"),
    TON("TONGA"),
    TTO("TRINIDAD OG TOBAGO"),
    TUN("TUNISIA"),
    TUR("TYRKIA"),
    TUV("TUVALU"),
    TWN("TAIWAN"),
    TZA("TANZANIA"),
    UGA("UGANDA"),
    UKR("UKRAINA"),
    UMI("MINDRE STILLEHAVSØYER"),
    URY("URUGUAY"),
    USA("USA"),
    UZB("UZBEKISTAN"),
    VAT("VATIKANSTATEN"),
    VCT("ST. VINCENT"),
    VEN("VENEZUELA"),
    VGB("JOMFRUØYENE BRIT."),
    VIR("JOMFRUØYENE AM."),
    VNM("VIETNAM"),
    VUT("VANUATU"),
    WLF("WALLIS/FUTUNAØYENE"),
    WSM("SAMOA"),
    XXK("KOSOVO"),
    XXX("STATSLØS"),
    YEM("JEMEN"),
    ZAF("SØR-AFRIKA"),
    ZMB("ZAMBIA"),
    ZWE("ZIMBABWE");

    companion object {
        private val log: Logger = LoggerFactory.getLogger(Landkode::class.java)
        private val kodeForUkjent = Pair("???", "UOPPGITT/UKJENT")

        fun dekode(kode: String): String {
            if (kodeForUkjent.first.equals(kode)) {
                return kodeForUkjent.second
            } else {
                try {
                    return Landkode.valueOf(kode).beskrivelse
                } catch (e: IllegalArgumentException) {
                    log.warn("Enum for kodeverk for landkode mangler gitt kode [" + kode + "]", e)
                    return "-"
                }
            }
        }
    }

}