package no.nav.personopplysninger.features.personalia.kodeverk

import org.slf4j.Logger
import org.slf4j.LoggerFactory

enum class Spraak(val beskrivelse: String) {
    AB("Abkhasisk"),
    AE("Avestisk"),
    AM("Amharisk"),
    AN("Aragonesisk"),
    AR("Arabisk"),
    AS("Assamesisk"),
    AV("Avarisk"),
    AZ("Aserbajdsjansk"),
    BA("Basjkirsk"),
    BE("Hviterussisk"),
    BG("Bulgarsk"),
    BO("Tibetansk"),
    BR("Bretonsk"),
    BS("Bosnisk"),
    CA("Katalansk"),
    CE("Tsjetsjensk"),
    CO("Korsiansk"),
    CS("Tsjekkisk"),
    CU("Kirkeslavisk"),
    CV("Tsjuvasjisk"),
    CY("Walisisk"),
    DA("Dansk"),
    DE("Tysk"),
    DV("Dhivehi"),
    EL("Gresk"),
    EN("Engelsk"),
    ES("Spansk"),
    ET("Estisk"),
    EU("Baskisk"),
    FA("Persisk"),
    FF("Fulfulde"),
    FI("Finsk"),
    FJ("Fijisk"),
    FO("Færøysk"),
    FR("Fransk"),
    GA("Irsk"),
    GD("Skotsk gælisk"),
    GL("Galisisk"),
    GV("Mansk"),
    HE("Hebraisk"),
    HR("Kroatisk"),
    HT("Haitisk kreolsk"),
    HU("Ungarsk"),
    HY("Armensk"),
    ID("Indonesisk"),
    II("Yi"),
    IK("Inupiak"),
    IS("Islandsk"),
    IT("Italiensk"),
    IU("Inuittisk"),
    JA("Japansk"),
    JV("Javanesisk"),
    KA("Georgisk"),
    KG("Kongolesisk"),
    KI("Kikuyu"),
    KJ("Kwanyama"),
    KK("Kasakhisk"),
    KL("Kalaallisut"),
    KO("Koreansk"),
    KU("Kurdisk"),
    KV("Syrjensk"),
    KW("Kornisk"),
    KY("Kirgisisk"),
    LB("Luxembourgsk"),
    LG("Luganda"),
    LI("Limburgisk"),
    LO("Laotisk"),
    LT("Litauisk"),
    LV("Latvisk"),
    MG("Gassisk"),
    MH("Marshallesisk"),
    MI("Maorisk"),
    MK("Makedonsk"),
    MN("Mongolsk"),
    MO("Moldovsk"),
    MS("Malayisk"),
    MT("Maltesisk"),
    MY("Burmesisk"),
    NA("Naurisk"),
    NB("Norsk"),
    ND("Nord-ndebele"),
    NL("Nederlandsk"),
    NN("Nynorsk"),
    NO("Norsk"),
    NR("Sør-ndebele"),
    NV("Navajo"),
    NY("Chichewa"),
    OC("Oksitansk"),
    OS("Ossetisk"),
    PA("Punjabi"),
    PL("Polsk"),
    PT("Portugesisk"),
    RM("Retoromansk"),
    RN("Kirundi"),
    RO("Rumesk"),
    RU("Russisk"),
    SC("Sardisk"),
    SE("Nord Samisk"),
    SI("Singalesisk"),
    SK("Slovakisk"),
    SL("Slovensk"),
    SM("Samoansk"),
    SO("Somalisk"),
    SQ("Albansk"),
    SR("Serbisk"),
    ST("Sesotho"),
    SU("Sudanesisk"),
    SV("Svensk"),
    TA("Tamilsk"),
    TG("Tadsjikisk"),
    TK("Turkmensk"),
    TO("Tonganesisk"),
    TR("Tyrkisk"),
    TT("Tatarsk"),
    TY("Tahitisk"),
    UG("Uigurisk"),
    UK("Ukrainsk"),
    UZ("Usbekisk"),
    VE("Tshivenda"),
    VI("Vietnamesisk"),
    VO("Volap³k"),
    WA("Vallonsk"),
    YI("Jiddisk"),
    YO("Joruba"),
    ZA("Zhuang, Chuang"),
    ZH("Kinesisk");

    companion object {
        private val log: Logger = LoggerFactory.getLogger(Spraak::class.java)

        fun dekode(kode: String): String {
            try {
                return Spraak.valueOf(kode).beskrivelse
            } catch (e: IllegalArgumentException) {
                log.warn("Enum for kodeverk for språk mangler gitt kode [" + kode + "]", e)
                return "-"
            }
        }
    }

}