/**
 * TPS-PROXY API
 * <h4>Api for Tps-Proxy</h4><a href=\"https://confluence.adeo.no/display/FEL/TPS+-+Tjeneste+MQ+S301+-+Hent+Innsynsopplysninger+for+en+person\">Confluence for tps innsyn</a>
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package no.nav.personopplysninger.features.personalia.dto.outbound

import java.util.*

data class Adresseinfo(
        val boadresse: Boadresse? = null,
        val geografiskTilknytning: GeografiskTilknytning? = null,
        val postadresse: Postadresse? = null,
        val prioritertAdresse: KodeMedDatoOgKilde? = null,
        val tilleggsadresse: Tilleggsadresse? = null,
        val utenlandskAdresse: UtenlandskAdresse? = null,
        val kilder: MutableSet<Kilde> = mutableSetOf() // TODO Are: Må typen være Array<String> for at den skal kunne mappes til JSON?
)