/**
* TPS-PROXY API
* <h4>Api for Tps-Proxy</h4><a href=\"https://confluence.adeo.no/display/FEL/TPS+-+Tjeneste+MQ+S301+-+Hent+Innsynsopplysninger+for+en+person\">Confluence for tps innsyn</a>
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package no.nav.personopplysninger.features.personalia.dto.outbound



/**
 * Informasjon om boadresse
 * @param adresse Primæradresse
 * @param adressetillegg Adressetillegg
 * @param bydel Bydel
 * @param datoFraOgMed Dato gyldig gyldig, format (ISO-8601): yyyy-MM-dd
 * @param kilde 
 * @param kommune Kommune
 * @param landkode Landkode
 * @param matrikkeladresse 
 * @param postnummer Postnummer
 * @param veiadresse 
 */
data class Boadresse (

    /* Primæradresse */
    val adresse: String? = null,
    /* Adressetillegg */
    val adressetillegg: String? = null,
    /* Bydel */
    val bydel: String? = null,
    /* Dato gyldig gyldig, format (ISO-8601): yyyy-MM-dd */
    val datoFraOgMed: String? = null,
    val kilde: String? = null,
    /* Kommune */
    val kommune: String? = null,
    /* Landkode */
    val landkode: String? = null,
    val matrikkeladresse: Matrikkeladresse? = null,
    /* Postnummer */
    val postnummer: String? = null,
    val veiadresse: Veiadresse? = null
) {
}