/**
* TPS-PROXY API
* <h4>Api for Tps-Proxy</h4><a href=\"https://confluence.adeo.no/display/FEL/TPS+-+Tjeneste+MQ+S301+-+Hent+Innsynsopplysninger+for+en+person\">Confluence for tps innsyn</a>
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package no.nav.personopplysninger.features.personalia.dto.outbound


/**
 * 
 * @param datoFraOgMed Dato gyldig gyldig, format (ISO-8601): yyyy-MM-dd
 * @param familienavnFodt Familienavn
 * @param farsFamilenavn Etternavn far
 * @param farsFornavn Fornavn far
 * @param foedested Fødested
 * @param fornavnFodt Fornavn
 * @param idOff Utenlandsk id
 * @param institusjon Instutisjon
 * @param institusjonNavn InstutisjonNavn
 * @param kilde 
 * @param kildePin Kilde pinnummer
 * @param land 
 * @param morsFamilenavn Etternavn mor
 * @param morsFornavn Fornavn mor
 * @param nasjonalId Nasjonal id
 * @param nasjonalitet 
 * @param sedRef 
 * @param sektor 
 */
data class Informasjon_om_person_utland (

    /* Dato gyldig gyldig, format (ISO-8601): yyyy-MM-dd */
    val datoFraOgMed: String? = null,
    /* Familienavn */
    val familienavnFodt: String? = null,
    /* Etternavn far */
    val farsFamilenavn: String? = null,
    /* Fornavn far */
    val farsFornavn: String? = null,
    /* Fødested */
    val foedested: String? = null,
    /* Fornavn */
    val fornavnFodt: String? = null,
    /* Utenlandsk id */
    val idOff: String? = null,
    /* Instutisjon */
    val institusjon: String? = null,
    /* InstutisjonNavn */
    val institusjonNavn: String? = null,
    val kilde: String? = null,
    /* Kilde pinnummer */
    val kildePin: String? = null,
    val land: Kode? = null,
    /* Etternavn mor */
    val morsFamilenavn: String? = null,
    /* Fornavn mor */
    val morsFornavn: String? = null,
    /* Nasjonal id */
    val nasjonalId: String? = null,
    val nasjonalitet: Kode? = null,
    val sedRef: String? = null,
    val sektor: Kode? = null
) {
}