/**
* TPS-PROXY API
* <h4>Api for Tps-Proxy</h4><a href=\"https://confluence.adeo.no/display/FEL/TPS+-+Tjeneste+MQ+S301+-+Hent+Innsynsopplysninger+for+en+person\">Confluence for tps innsyn</a>
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package no.nav.personopplysninger.features.personalia.dto.outbound



/**
 * Objekt retunert fra person-endepunktet
 * @param adresseinfo 
 * @param alder Alder
 * @param antallBarn Antall barn
 * @param antallLevendeBarnUnder18 Antall levende barn under 18
 * @param brukerbehovListe 
 * @param datoFraOgMed 
 * @param doedsdato 
 * @param egenansatt 
 * @param foedselsdato Dato født, format (ISO-8601): yyyy-MM-dd
 * @param foedtIKommune 
 * @param foedtILand 
 * @param foreldreansvar 
 * @param ident Personidentifikator
 * @param identtype 
 * @param innvandringUtvandring 
 * @param kilde Fra hvor informasjonen er oppgitt
 * @param kjonn Kjonn
 * @param kontonummer 
 * @param navn 
 * @param oppholdstillatelse 
 * @param relasjonFinnes Om personen har en relasjon(ektefelle)
 * @param sivilstand 
 * @param spesiellOpplysning 
 * @param spraak 
 * @param statsborgerskap 
 * @param status 
 * @param telefon 
 * @param tiltak 
 * @param utenlandsinfoList 
 * @param utenlandskBank 
 * @param vergemaalListe 
 */
data class Personinfo (

    val adresseinfo: Adresseinfo? = null,
    /* Alder */
    val alder: kotlin.Int? = null,
    /* Antall barn */
    val antallBarn: kotlin.Int? = null,
    /* Antall levende barn under 18 */
    val antallLevendeBarnUnder18: kotlin.Int? = null,
    val brukerbehovListe: kotlin.Array<KodeMedDatoOgKilde>? = null,
    val datoFraOgMed: kotlin.String? = null,
    val doedsdato: Doedsdato? = null,
    val egenansatt: Egenansatt? = null,
    /* Dato født, format (ISO-8601): yyyy-MM-dd */
    val foedselsdato: kotlin.String? = null,
    val foedtIKommune: Kode? = null,
    val foedtILand: Kode? = null,
    val foreldreansvar: KodeMedDatoOgKilde? = null,
    /* Personidentifikator */
    val ident: kotlin.String? = null,
    val identtype: Kode? = null,
    val innvandringUtvandring: InnvandringUtvandring? = null,
    /* Fra hvor informasjonen er oppgitt */
    val kilde: kotlin.String? = null,
    /* Kjonn */
    val kjonn: kotlin.String? = null,
    val kontonummer: Kontonummer? = null,
    val navn: Navn? = null,
    val oppholdstillatelse: KodeMedDatoOgKilde? = null,
    /* Om personen har en relasjon(ektefelle) */
    val relasjonFinnes: kotlin.Boolean? = null,
    val sivilstand: KodeMedDatoOgKilde? = null,
    val spesiellOpplysning: KodeMedDatoOgKilde? = null,
    val spraak: KodeMedDatoOgKilde? = null,
    val statsborgerskap: KodeMedDatoOgKilde? = null,
    val status: KodeMedDatoOgKilde? = null,
    val telefon: Telefoninfo? = null,
    val tiltak: Tiltak? = null,
    val utenlandsinfoList: kotlin.Array<Informasjon_om_person_utland>? = null,
    val utenlandskBank: UtenlandskBank? = null,
    val vergemaalListe: kotlin.Array<Vergemaal>? = null
) {
}