/**
 * TPS-PROXY API
 * <h4>Api for Tps-Proxy</h4><a href=\"https://confluence.adeo.no/display/FEL/TPS+-+Tjeneste+MQ+S301+-+Hent+Innsynsopplysninger+for+en+person\">Confluence for tps innsyn</a>
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package no.nav.personopplysninger.features.personalia.dto.outbound


data class Personinfo(
        val adresseinfo: Adresseinfo? = null,
        /* Alder */
        val alder: kotlin.Int? = null,
        /* Antall barn */
        val antallBarn: kotlin.Int? = null,
        /* Antall levende barn under 18 */
        val antallLevendeBarnUnder18: kotlin.Int? = null,
        val brukerbehovListe: kotlin.Array<KodeMedDatoOgKilde>? = null,
        val datoFraOgMed: String? = null,
        val doedsdato: Doedsdato? = null,
        val egenansatt: Egenansatt? = null,
        /* Dato født, format (ISO-8601): yyyy-MM-dd */
        val foedselsdato: String? = null,
        val foedtIKommune: Kode? = null,
        val foedtILand: Kode? = null,
        val foreldreansvar: KodeMedDatoOgKilde? = null,
        /* Personidentifikator */
        val ident: String? = null,
        val identtype: Kode? = null,
        val innvandringUtvandring: InnvandringUtvandring? = null,
        /* Fra hvor informasjonen er oppgitt */
        val kilde: String? = null,
        /* Kjonn */
        val kjonn: String? = null,
        val kontonummer: String? = null,
        val navn: Navn? = null,
        val oppholdstillatelse: KodeMedDatoOgKilde? = null,
        /* Om personen har en relasjon(ektefelle) */
        val relasjonFinnes: kotlin.Boolean? = null,
        val sivilstand: KodeMedDatoOgKilde? = null,
        val spesiellOpplysning: KodeMedDatoOgKilde? = null,
        val spraak: String? = null,
        val statsborgerskap: KodeMedDatoOgKilde? = null,
        val status: KodeMedDatoOgKilde? = null,
        val telefon: Tlfnr? = null,
        val tiltak: Tiltak? = null,
        val utenlandsinfoList: kotlin.Array<Informasjon_om_person_utland>? = null,
        val utenlandskBank: UtenlandskBank? = null,
        val vergemaalListe: kotlin.Array<Vergemaal>? = null,
        val fnr: String? = null
)