/**
* TPS-PROXY API
* <h4>Api for Tps-Proxy</h4><a href=\"https://confluence.adeo.no/display/FEL/TPS+-+Tjeneste+MQ+S301+-+Hent+Innsynsopplysninger+for+en+person\">Confluence for tps innsyn</a>
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package no.nav.personopplysninger.features.personalia.dto.outbound


/**
 * Informasjon om postadresse
 * @param adresse1 Adresse1
 * @param adresse2 Adresse2
 * @param adresse3 Adresse3
 * @param datoFraOgMed Dato gyldig gyldig, format (ISO-8601): yyyy-MM-dd
 * @param kilde 
 * @param land Land
 * @param postnummer Postnummer
 */
data class Postadresse (

    /* Adresse1 */
    val adresse1: kotlin.String? = null,
    /* Adresse2 */
    val adresse2: kotlin.String? = null,
    /* Adresse3 */
    val adresse3: kotlin.String? = null,
    /* Dato gyldig gyldig, format (ISO-8601): yyyy-MM-dd */
    val datoFraOgMed: kotlin.String? = null,
    val kilde: kotlin.String? = null,
    /* Land */
    val land: kotlin.String? = null,
    /* Postnummer */
    val postnummer: kotlin.String? = null
) {
}