/**
* TPS-PROXY API
* <h4>Api for Tps-Proxy</h4><a href=\"https://confluence.adeo.no/display/FEL/TPS+-+Tjeneste+MQ+S301+-+Hent+Innsynsopplysninger+for+en+person\">Confluence for tps innsyn</a>
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package no.nav.personopplysninger.features.personalia.dto.outbound


/**
 * Telefon kontaktinformasjon
 * @param jobb Telefonnummer jobb
 * @param jobbDatoRegistrert Dato jobb telefonnummer registert, format (ISO-8601): yyyy-MM-dd
 * @param jobbKilde 
 * @param mobil Telefonnummer mobil
 * @param mobilDatoRegistrert Dato mobil telefonnummer registert, format (ISO-8601): yyyy-MM-dd
 * @param mobilKilde 
 * @param privat Telefonnummer privat
 * @param privatDatoRegistrert Dato privat telefonnummer registert, format (ISO-8601): yyyy-MM-dd
 * @param privatKilde 
 */
data class Telefoninfo (

    /* Telefonnummer jobb */
    val jobb: kotlin.String? = null,
    /* Dato jobb telefonnummer registert, format (ISO-8601): yyyy-MM-dd */
    val jobbDatoRegistrert: kotlin.String? = null,
    val jobbKilde: kotlin.String? = null,
    /* Telefonnummer mobil */
    val mobil: kotlin.String? = null,
    /* Dato mobil telefonnummer registert, format (ISO-8601): yyyy-MM-dd */
    val mobilDatoRegistrert: kotlin.String? = null,
    val mobilKilde: kotlin.String? = null,
    /* Telefonnummer privat */
    val privat: kotlin.String? = null,
    /* Dato privat telefonnummer registert, format (ISO-8601): yyyy-MM-dd */
    val privatDatoRegistrert: kotlin.String? = null,
    val privatKilde: kotlin.String? = null
) {
}