/**
* TPS-PROXY API
* <h4>Api for Tps-Proxy</h4><a href=\"https://confluence.adeo.no/display/FEL/TPS+-+Tjeneste+MQ+S301+-+Hent+Innsynsopplysninger+for+en+person\">Confluence for tps innsyn</a>
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package no.nav.personopplysninger.features.personalia.dto.outbound


/**
 * Informasjon om utenlandsk bank
 * @param adresse1 Bank adresselinje 1
 * @param adresse2 Bank adresselinje 2
 * @param adresse3 Bank adreeselinje 3
 * @param bankkode Bankkode
 * @param banknavn Banknavn
 * @param datoFraOgMed Dato gyldig gyldig, format (ISO-8601): yyyy-MM-dd
 * @param iban IBAN
 * @param kilde 
 * @param kontonummer Kontonummer
 * @param land 
 * @param swiftkode Swift kode
 * @param valuta 
 */
data class UtenlandskBank (

    /* Bank adresselinje 1 */
    val adresse1: String? = null,
    /* Bank adresselinje 2 */
    val adresse2: String? = null,
    /* Bank adreeselinje 3 */
    val adresse3: String? = null,
    /* Bankkode */
    val bankkode: String? = null,
    /* Banknavn */
    val banknavn: String? = null,
    /* Dato gyldig gyldig, format (ISO-8601): yyyy-MM-dd */
    val datoFraOgMed: String? = null,
    /* IBAN */
    val iban: String? = null,
    val kilde: String? = null,
    /* Kontonummer */
    val kontonummer: String? = null,
    val land: Kode? = null,
    /* Swift kode */
    val swiftkode: String? = null,
    val valuta: Kode? = null
) {
}