package no.nav.personopplysninger.features.person.model.dto

data class PersonInformasjon(
        val adresseinfo: Adresseinfo? = null,
        val barnListe: List<Barn> = emptyList(),
        val brukerbehovListe: List<BrukerbehovListe> = emptyList(),
        val datoFraOgMed: String? = null,
        val doedsdato: Doedsdato? = null,
        val egenansatt: Egenansatt? = null,
        val foedselsdato: String? = null,
        val foedtIKommune: String? = null,
        val foedtILand: String? = null,
        val foreldreansvar: Foreldreansvar? = null,
        val ident: String? = null,
        val identtype: String? = null,
        val innvandringUtvandring: InnvandringUtvandring? = null,
        val kilde: String? = null,
        val kjonn: String? = null,
        val kontonummer: Kontonummer? = null,
        val navn: Navn? = null,
        val oppholdstillatelse: Oppholdstillatelse? = null,
        val relasjon: Relasjon? = null,
        val samboer: Samboer? = null,
        val sivilstand: Sivilstand? = null,
        val spesreg: Spesreg? = null,
        val spraak: Spraak? = null,
        val statsborgerskap: Statsborgerskap? = null,
        val status: Status? = null,
        val telefon: Telefon = Telefon(),
        val tiltak: Tiltak? = null,
        val utenlandsinfoList: List<Utenlandsinfo> = emptyList(),
        val utenlandskBank: UtenlandskBank? = null,
        val vergemaalListe: List<VergemaalListe> = emptyList()
)
