package no.nav.personopplysninger_backend.modell.person

data class PersonInformasjon(
        val adresseinfo: Adresseinfo? = null,
        val barnListe: List<BarnListe> = emptyList(),
        val brukerbehovListe: List<BrukerbehovListe> = emptyList(),
        val datoFraOgMed: String,
        val doedsdato: Doedsdato? = null,
        val egenansatt: Egenansatt? = null,
        val foedselsdato: String,
        val foedtIKommune: String = "",
        val foedtILand: String = "",
        val foreldreansvar: Foreldreansvar? = null,
        val ident: String,
        val identtype: String,
        val innvandringUtvandring: InnvandringUtvandring? = null,
        val kilde: String = "",
        val kjonn: String,
        val kontonummer: Kontonummer? = null,
        val navn: Navn,
        val oppholdstillatelse: Oppholdstillatelse? = null,
        val relasjon: Relasjon? = null,
        val samboer: Samboer? = null,
        val sivilstand: Sivilstand,
        val spesreg: Spesreg? = null,
        val spraak: Spraak? = null,
        val statsborgerskap: Statsborgerskap? = null,
        val status: Status? = null,
        val telefon: Telefon? = null,
        val tiltak: Tiltak? = null,
        val utenlandsinfoList: List<Utenlandsinfo> = emptyList(),
        val utenlandskBank: UtenlandskBank? = null,
        val vergemaalListe: List<VergemaalListe> = emptyList()
)