package no.nav.personopplysninger_backend.modell.person

data class PersonInformasjon(
        val adresseinfo: Adresseinfo,
        val barnListe: List<BarnListe>,
        val brukerbehovListe: List<BrukerbehovListe>,
        val datoFraOgMed: String,
        val doedsdato: Doedsdato,
        val egenansatt: Egenansatt,
        val foedselsdato: String,
        val foedtIKommune: String,
        val foedtILand: String,
        val foreldreansvar: Foreldreansvar,
        val ident: String,
        val identtype: String,
        val innvandringUtvandring: InnvandringUtvandring,
        val kilde: String,
        val kjonn: String,
        val kontonummer: Kontonummer,
        val navn: Navn,
        val oppholdstillatelse: Oppholdstillatelse,
        val relasjon: Relasjon,
        val samboer: Samboer,
        val sivilstand: Sivilstand,
        val spesreg: Spesreg,
        val spraak: Spraak,
        val statsborgerskap: Statsborgerskap,
        val status: Status,
        val telefon: Telefon,
        val tiltak: Tiltak,
        val utenlandsinfoList: List<Utenlandsinfo>,
        val utenlandskBank: UtenlandskBank,
        val vergemaalListe: List<VergemaalListe>
)