apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: personopplysninger-api
  namespace: personbruker
  labels:
    team: personbruker
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /person/personopplysninger-api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /person/personopplysninger-api/internal/isAlive
    initialDelay: 10
  prometheus:
    enabled: true
    path: /person/personopplysninger-api/internal/metrics
  replicas:
    min: {{ min-replicas }}
    max: {{ max-replicas }}
  webproxy: true
  tokenx:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
  kafka:
    pool: {{ kafka-pool }}
  accessPolicy:
    outbound:
      external:
        - host: kodeverk-api.nav.no
        - host: {{ norg2-host }}
        - host: {{ digdir-krr-proxy-host }}
        - host: {{ pdl-mottak-host }}
        - host: {{ pdl-api-host }}
        - host: {{ inst2-host }}
        - host: {{ medlemskap-host }}
        - host: {{ kontoregister-host }}
  ingresses:
  {{#each ingresses}}
     - "{{this}}"
         {{/each}}
  envFrom:
    - secret: personopplysninger-api-secret
  secureLogs:
    enabled: true
  resources:
    limits:
      memory: 768Mi
    requests:
      cpu: 100m
      memory: 384Mi
