apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: personopplysninger-api
  namespace: personbruker
  labels:
    team: personbruker
spec:
  image: {{version}}
  port: 8080
  liveness:
    path: /person/personopplysninger-api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /person/personopplysninger-api/internal/isAlive
    initialDelay: 10
  prometheus:
    enabled: true
    path: /person/personopplysninger-api/internal/metrics
  replicas:
    min: 2
    max: 4
  webproxy: true
  tokenx:
    enabled: true
  accessPolicy:
    rules:
      - application: personopplysninger-proxy
        namespace: personbruker
        cluster: {{ fss-cluster }}
      - application: pdl-mottak
        namespace: personbruker
        cluster: {{ fss-cluster }}
      - application: digdir-krr-proxy
        namespace: team-rocket
      - application: pdl-api
        namespace: pdl
        cluster: {{ fss-cluster }}
    outbound:
      external:
        - host: {{ proxy-host }}
        - host: {{ pdl-api-host }}
        - host: {{ pdl-mottak-host }}
  ingresses:
  {{#each ingresses}}
     - "{{this}}"
         {{/each}}
  envFrom:
    - configmap: loginservice-idporten
    - secret: personopplysninger-api-secret
  secureLogs:
    enabled: true
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "500m"
      memory: 384Mi
