package no.nav.personopplysninger.personalia.enums

enum class AdresseMappingType {
    INNLAND_VEGADRESSE, INNLAND_POSTBOKSADRESSE, INNLAND_FRIFORMADRESSE, UTLAND_ADRESSE, UTLAND_FRIFORMADRESSE, MATRIKKELADRESSE, UKJENT_BOSTED, EMPTY
}