name: Deploy to dev
on:
  workflow_dispatch

jobs:
  deploy:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    environment: dev-gcp:personbruker
    env:
      version: ghcr.io/${{ github.repository }}:${{ github.sha }}
      team: personbruker
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: nais/login@v0
        with:
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          team: ${{env.team}}
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 1.17
      - name: Setup cache
        uses: actions/cache@v3
        with:
          path: '~/.gradle/caches
        ~/.gradle/wrapper'
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}
      - name: Build application
        run: |
          ./gradlew clean build
      - uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: ${{env.team}}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
      - name: Deploy to dev-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: dev-gcp
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: ./nais/nais.yaml
          VAR: version=${{ env.version }}
          VARS: ./nais/dev-gcp/personbruker.json
