name: Deploy alerts to dev
on:
  push

jobs:
  apply-alerts:
    name: Apply alerts to cluster
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: deploy to dev
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: ./nais/alerts.yaml